# .readthedocs.yml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools: {python: "3.12"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
      - poetry self add poetry-plugin-export
      - poetry export
        --only main --only docs
        --extras check_laws --extras compatible_mypy
        --format=requirements.txt
        --output=requirements.txt

python:
  install:
    - requirements: requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: all
