# (generated with --quick)

from typing import Any, Callable

def bind(function) -> Callable[[Any], Any]: ...
def rescue(function) -> Callable[[Any], Any]: ...
def unify(function) -> Callable[[Any], Any]: ...
